### ISSUE TITLE
New processor - rk

### ISSUE THREAD

**Issue by M0rdecay** [gekatateam/neptunus#43]
Rk processor rewrites event routing key like:
```toml
[[processors]]
  [processors.rk.mapping]
    new_key = "/an/old/key"
    "other.key" = "other.old.routing.key"
```
